blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from blog.views import CreatePost, HomePage, Details, Delete

urlpatterns = [

	url(r'^register$', User_Register.as_view(), name='register'),

	url(r'^create$', CreatePost.as_view(), name = "create"),

	url(r'^details/(?P<slug>[0-9A-Za-z-]+)', Details.as_view(), name = "details"),

	url(r'^delete/(?P<slug>[0-9A-Za-z-]+)', Delete.as_view(), name = "delete")



]

user_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from blog.views import CreatePost, HomePage

urlpatterns = [

	url(r'^$', HomePage.as_view(), name="index"),

	url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.







class Posts(models.Model):
	title = models.CharField(max_length = 60)
	content = models.TextField()
	created_at = models.DateTimeField(editable=False)
	updated_at = models.DateTimeField()
	slug = models.SlugField(max_length=60)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		self.updated_at = timezone.now()

		if not self.id:
			self.created_at = timezone.now()
		super(Posts, self).save(*args,**kwargs)

	def __str__(self):
		return self.title

blog/forms.py
from django import forms
from .models import Posts

class PostForm(forms.ModelForm):
	class Meta:
		model = Posts
		fields =[
		"title",
		"content",

		]

blog/views.py
from django.shortcuts import render,redirect
from blog.models import Posts
from .forms import PostForm
from django.views.generic import View
from django.shortcuts import get_object_or_404



# Create your views here.


class HomePage(View):
	template = "index.html"

	def get(self,request):
		post_lists = Posts.objects.all()

		context = {
			"posts": post_lists
		}

		return render(request, self.template,  context)




class CreatePost(View):

	form = PostForm

	template = "create.html"

	def get(self,request):

			context={
			"form":PostForm

			}
			return render(request, self.template, context)


	def post(self,request):

		form = PostForm(request.POST)

		if form.is_valid():
			form.save()
			return redirect("index")

		return redirect("create")

class Details(View):

	def get(self,request, slug):

		task = get_object_or_404(Posts,slug=slug)

		form = PostForm(instance=task)

		context={

			"post": task,
			"form":form,

		}

		return render(request, 'details.html', context)

		
	def post(self,request,slug):
		task = get_object_or_404(Posts,slug=slug)


		form = PostForm(request.POST,instance = task)
		if form.is_valid():
			form.save()
			return redirect("index")

		context={
			"post": task,
			"form":form,
		}

		return render(request, 'details.html', context)


class Delete(View):

	def post(self,request,slug):
		obj = get_object_or_404(Posts,slug=slug)
		obj.delete()
		return redirect("index")


class User_Registration(View):

	template = "registration.html"

	def get(self,request):
		if self.user.is_authenticated():
			return render(request,"index.html",{})
		user_form = UserForm()
		context={
			"user_form" = user_form
		}
		return render(request,self.template, context)

	def post(self,request):
		user_form = UserForm(data=request.POST)

		if user_form.is_valid():
			user = user_form.save()
		else:
			context={
				'user_form': user_form,
			}
		return render(request,self.template, context)

		






		

blog/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>

	<form action="{% url 'blog:create' %}" method = "POST">
		{% csrf_token %}
		
		{{form.as_p}}
		<input type = "submit" value="submit">
	</form>

	
</body>
</html>

blog/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>details</title>
</head>
<body>
	<form action="{% url 'blog:details' slug=post.slug %}" method = "POST">
		{% csrf_token %}
		
		{{form.as_p}}
		<input type = "submit" value="submit">
	</form>

	<form action="{% url 'blog:delete' slug=post.slug %}" method="POST">
        {% csrf_token %}


        <input id = "delete" type="submit" class ="deletebutton" value="Delete">
    </form>
</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="UTF-8">
    <title>Bloggy: A Blog about Blogs</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/css/foundation.css" />
</head>
<body>
	
	{% for post in posts %}
	
	<div class = "row"> 

		<h2><a href="{% url 'blog:details' slug=post.slug %}"> {{post.title}}</a></h2>
		<p>{{post.content}}</p>
		<p>created at: {{post.created_at}}</p>



	</div>
	{% endfor %}

	<a href="{% url 'blog:create' %}"> create</a>
	
</body>
</html>

blog/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<form method = "POST" action="{% url 'blog:register'%}">
		{% csrf_token %}
		{{user_form}}
		
	<input type="submit" name="submit" value="Register" />


	</form>
</body>
</html>